#pragma config(Sensor, S1,     T,              sensorNone)
#pragma config(Motor,  motorA,          M,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          L,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          R,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//playSound(soundBeepBeep);
	//wait1Msec(1000);

	//setLEDColor(ledOrangePulse);
	//wait1Msec(1000);

	//displayCenteredBigTextLine(5,"Hello");
	//wait1Msec(1000);

	//motor[motorB]=30;
	//motor[motorC]=30;
	//wait1Msec(1000);
	//motor[motorB]=30;
	//motor[motorC]=-30;
	//wait1Msec(1000);
	//motor[motorB]=30;
	//motor[motorC]=30;
	//wait1Msec(1000);
	motor[motorB]=30;
	motor[motorC]=30;
	while(SensorValue[S1]==0)
	{
		//displayCenteredBigTextLine(3, "Touch Sensor: %d", SensorValue[S1]);
	}
	motor[motorB]=0;
		motor[motorC]=0;
}
