#pragma config(Sensor, S1,     t,              sensorEV3_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		displayCenteredBigTextLine (3, "Touch sensor: %d", SensorValue[S1]);
	}


}
