#pragma config(Motor,  motorA,          M,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          L,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          R,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	moveMotorTarget(motorB, 500,50);
	moveMotorTarget(motorC, 500,50);
	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);

	motor(motorB)= 50;
	motor(motorA)= 0;
	wait1Msec(3000);
	moveMotorTarget(motorB, 500,50);
	moveMotorTarget(motorC, 500,50);
	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);

	motor(motorB)= 50;
	motor(motorA)= 0;
	wait1Msec(3000);
	moveMotorTarget(motorB, 500,50);
	moveMotorTarget(motorC, 500,50);
	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);

	motor(motorB)= 50;
	motor(motorA)= 0;
	wait1Msec(3000);

}
