#pragma config(Sensor, S1,     t,              sensorEV3_Touch)
#pragma config(Motor,  motorA,          m,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          l,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          r,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(motorB, 50);
	setMotorSpeed(motorC, 50);
	while(SensorValue[t]==0) {};


}
