#pragma config(Sensor, S1,     T,              sensorEV3_Touch)
#pragma config(Motor,  motorA,          M,             tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          L,             tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          R,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB]=30;
	motor[motorC]=30;
	while(SensorValue[S1]==0)
	{
	}
	motor[motorB]=-30;
	motor[motorC]=-30;
	playSound(soundLowBuzz);
	wait1Msec(1000);
	motor[motorC]=30;
	motor[motorB]=-10;
	displayTextLine(1,"left");
	wait1Msec(1000);
	motor[motorB]=30;
	motor[motorC]=30;
	while(SensorValue[S1]==0)
	{
	}
	motor[motorB]=-30;
	motor[motorC]=-30;
	wait1Msec(1000);
	motor[motorB]=30;
	motor[motorC]=-10;
	wait1Msec(1000);
	motor[motorB]=-30;
	motor[motorC]=-30;
	wait1Msec(1000);
}
